# Service declaration
apiVersion: v1
kind: Service
metadata:
  name: code-executor-service
  labels:
    app: code-executor
spec:
  type: LoadBalancer
  selector:
    app: code-executor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
