apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: code-executor-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: code-executor-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
