# Deployment declaration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-executor-deployment
  labels:
    app: code-executor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: code-executor
  template:
    metadata:
      labels:
        app: code-executor
    spec:
      containers:
        - name: code-executor
          image: gcr.io/cloud-executor/code-executor:0.1.3
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
